---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc-storage
  namespace: grafana-dev
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tanzu-storage-computer
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc-plugins
  namespace: grafana-dev
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tanzu-storage-computer
  resources:
    requests:
      storage: 10Gi
